from . import env
import os

MAX_RETRIEVED_MEMORIES = 10

DECAY_DAYS_EMOTION = 7
DECAY_DAYS_GENERAL = 60
DECAY_DAYS_MOOD = 3

EMBEDDING_CACHE_MAX_SIZE = 1000
EMBEDDING_MAX_TEXT_LENGTH = 8000
EMBEDDING_OUTPUT_DIM = 768
EMBEDDING_MIN_TEXT_LEN = 6
EMBEDDING_CACHE_TTL_SECONDS = 86400
EMBEDDING_INFLIGHT_WAIT_SECONDS = 15
EMBEDDING_SOFT_TPM_LIMIT = 30000
EMBEDDING_SOFT_RPM_LIMIT = 100

API_KEY_FAILURE_THRESHOLD = 3
API_KEY_RECOVERY_TIME = 300
API_KEY_SUCCESS_THRESHOLD = 2

MAX_MEMORIES_DISPLAY = 12

MAX_FILE_SIZE = 20 * 1024 * 1024
ALLOWED_EXTENSIONS = {
    ".txt",
    ".md",
    ".py",
    ".json",
    ".csv",
    ".html",
    ".js",
    ".css",
    ".xml",
    ".yaml",
    ".yml",
    ".log",
    ".ini",
}

MAX_TG_LEN = 4000

CHUNK_SIZE = 1500
CHUNK_OVERLAP = 120
DOC_EMBED_BATCH_SIZE = 24

CHAT_MAX_RETRIES = 5
CHAT_BASE_RETRY_DELAY = 1
HIGH_DEMAND_BASE_DELAY = 1.5
HIGH_DEMAND_MAX_DELAY = 20.0
HIGH_DEMAND_MODEL_COOLDOWN = 30.0
PROACTIVE_MIN_SEND_GAP_SECONDS = 1800
PROACTIVE_DECISION_MAX_RETRIES = 3
PROACTIVE_DECISION_BASE_DELAY = 1.2
PROACTIVE_DECISION_MAX_DELAY = 8.0
PROACTIVE_SCORE_THRESHOLD = 2.5
PROACTIVE_URGENT_SCHEDULE_MINUTES = 30
PROACTIVE_REPEAT_WINDOW_SECONDS = 3600
PROACTIVE_REPEAT_SIMILARITY_THRESHOLD = 0.72
PROACTIVE_POLICY_CACHE_SECONDS = 21600
PROACTIVE_MAX_STM_TURNS = 24
PROACTIVE_MAX_STM_CHARS = 6000
MAX_OUTPUT_TOKENS = 512
TEMPERATURE = 0.75
TOP_P = 0.95

MAX_HISTORY_LEN = 400
HISTORY_TOKEN_BUDGET = 20000
HISTORY_SUMMARY_TRIGGER_RATIO = 0.90
HISTORY_SUMMARY_TARGET_RATIO = 0.70
HISTORY_SUMMARY_MIN_EXTRACT = 20
HISTORY_EST_CHARS_PER_TOKEN = 4
HISTORY_VISUAL_TOKEN_RATIO = 0.25
HISTORY_VISUAL_TOKEN_MIN = 1200
HISTORY_VISUAL_PART_TOKEN_BASE = 300
HISTORY_VISUAL_FACTOR_MIN = 0.50
HISTORY_VISUAL_FACTOR_MAX = 3.00
HISTORY_VISUAL_CALIBRATION_ALPHA = 0.15
HISTORY_IMAGE_MAX_SIDE = 768
HISTORY_RECENT_MEDIA_WINDOW = 20
VISUAL_UNIT_WEIGHT_IMAGE = 1.0
VISUAL_UNIT_WEIGHT_STICKER = 1.0
VISUAL_UNIT_WEIGHT_VIDEO = 3.0
VIDEO_VISUAL_TOKENS_PER_SECOND = 300.0
VIDEO_VISUAL_BASE_TOKENS = 100.0
INPUT_IMAGE_MEDIA_RESOLUTION = "medium"
STICKER_MEDIA_RESOLUTION = "low"

MAX_RAG_IMAGES = 2
MAX_HISTORY_IMAGE_PARTS = 5
MAX_IMAGE_PIXELS = 768
VIDEO_MAX_DURATION_SECONDS = 30
VIDEO_TARGET_HEIGHT = 720
VIDEO_SCALE_ALGO = "bicubic"
TOOL_MAX_REMOTE_CALLS = 20
TERMINAL_TOOL_MAX_OUTPUT_CHARS = 12000
DOCKER_COMPUTER_IMAGE = "openbot-ai-computer:latest"
DOCKER_COMPUTER_MEMORY_LIMIT = "4g"
